name: untitled3
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  shared_preferences: ^2.3.0
  http: ^1.6.0
  flutter:
    sdk: flutter
  image_picker: ^1.2.1
  flutter_svg:
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bg.svg
    - assets/icon/               # ⬅️ DAFTARKAN FOLDER ICON

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  image_path: "assets/icon/app_icon.png"
